###
POST  http://localhost:8081/user/deleteAll

POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###

POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf1"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
//create a new trail park
POST http://localhost:8081/parks/trailparks
Content-Type: application/json 

{
    "parkName": "manyTest",
    "description": "This is a many test",
    "address": "43 many Test Street",
    "photo": {
        "name": "Your Photo Name",
        "desc": "Your Photo Description",
        "link": "Your Photo Link"
    },
    "segments": [
        {"segmentID": "64b8503fa0a8c7f345b67ee4"},
        {"segmentID": "64b85012a0a8c7f345b67ee2"},
        {"segmentID": "64b84f77a0a8c7f345b67ede"},
        {"segmentID": "64b8507da0a8c7f345b67ee6"}
    ]
}


###
//Update trail park
POST http://localhost:8081/parks/trailparks
Content-Type: application/json 

{
    "parkName": "TestPark",
    "description": "This is a test",
    "address": "43 Test Street",
    "photo": {
        "name": "Your Photo Name",
        "desc": "Your Photo Description",
        "link": "Your Photo Link"
    },
    "segments": [
        {
            "segmentID": "64694d4eebcfe8e7f004dfc8",
        }
    ]
}
###
//get segment info by _id
GET http://localhost:8081/parks/segments/64b8503fa0a8c7f345b67ee4

###
//get all segments associated to a park _id
GET http://localhost:8081/parks/trailparks/getsegments/65038a78021afb7c4d9ba0d9

###
//get all trail parks
GET http://localhost:8081/parks/trailparks

###
//get all segments
GET http://localhost:8081/api/segments

###
//get all segments NOT WORKING
GET http://localhost:8081/feature/features
 
###
//create segment
POST http://localhost:8081/api/segments
Content-Type: application/json

{
    "segmentName": "Sample Segment",
    "description": "This is a sample segment.",
    "difficulty": "Intermediate",
    "park": "Sample Park",
    "Features": [
        {
            "featureName": "Sample Feature",
            "description": "This is a sample feature."
        }
    ]
}
