@baseurl = http://localhost:8081

###
POST  http://localhost:8081/user/deleteAll

POST http://localhost:8080/user/signup
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "email" : "cdon@gmail.com",
    "password" : "tochi12345"
}

###

POST http://localhost:8080/user/login
Content-Type: application/json 

{
    "username" : "tochiamanze",
    "password" : "tochi12345"
}

###
GET http://localhost:8081/user/getAll
Content-Type: application/json

###
Get http://localhost:8081/user/DerekMartineau
Content-Type: application/json

### GET USERNAME FROM ID
Get {{baseurl}}/user/useriD/654e930f78f09598d1a80561

###
POST http://localhost:8081/user/editUser
Content-Type: application/json 

{
    "userId" : "635ab8dfc407faf9f73deaf2",
    "username" : "Tochi Edit",
    "password" : "dwwrwr"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "640e316ceebb6807bae74c7b"
}

###
GET  http://localhost:8081/user/getUserById
Content-Type: application/json 

{
    "userId" : "634edb2a16710b2cda6fb370"
}

###
//create a new trail park
POST http://localhost:8081/parks/trailparks
Content-Type: application/json 

{
    "parkName": "manyTest",
    "description": "This is a many test",
    "address": "43 many Test Street",
    "photo": {
        "name": "Your Photo Name",
        "desc": "Your Photo Description",
        "link": "Your Photo Link"
    },
    "segments": [
        {"segmentID": "64b8503fa0a8c7f345b67ee4"},
        {"segmentID": "64b85012a0a8c7f345b67ee2"},
        {"segmentID": "64b84f77a0a8c7f345b67ede"},
        {"segmentID": "64b8507da0a8c7f345b67ee6"}
    ]
}


###
//Update trail park
POST http://localhost:8081/parks/trailparks
Content-Type: application/json 

{
    "parkName": "TestPark",
    "description": "This is a test",
    "address": "43 Test Street",
    "photo": {
        "name": "Your Photo Name",
        "desc": "Your Photo Description",
        "link": "Your Photo Link"
    },
    "segments": [
        {
            "segmentID": "64694d4eebcfe8e7f004dfc8",
        }
    ]
}
###
//get segment info by _id
GET http://localhost:8081/parks/segments/64b8503fa0a8c7f345b67ee4

###
//get all segments associated to a park _id
GET http://localhost:8081/parks/trailparks/getsegments/65038a78021afb7c4d9ba0d9

###
//get all trail parks
GET http://localhost:8081/parks/trailparks

###
//get all segments
GET http://localhost:8081/api/segments

###
//get all segments NOT WORKING
GET http://localhost:8081/feature/features
 
###
//create segment
POST http://localhost:8081/api/segments
Content-Type: application/json

{
    "segmentName": "Walls",
    "description": "Chunky gravel doubletrack down until the trail thins at a rocky ledge and then passes over a board to avoid an often swampy pit. You can do a nice drop off either of the loamy edges at the top of the downhill.",
    "difficulty": "Intermediate",
    "park": "Gordon College",
    "features": [
        {"featureID":"656f862d19113e0adce02c80"},
        {"featureID":"656f863219113e0adce02c82"},
        {"featureID":"656f863719113e0adce02c84"},
        {"featureID":"656f862d19113e0adce02c86"},
        {"featureID":"656f862d19113e0adce02c88"},
        {"featureID":"656f862d19113e0adce02c8a"}
    ]
}




###
# Update Feature
PUT http://localhost:8081/api/features/652589d43c47bb139f820ec9
Content-Type: application/json

{
  "featureName": "Updated Feature Name",
  "description": "Updated Feature Description",
  "photo": {
    "name": "Updated Photo Name",
    "desc": "Updated Photo Description",
    "link": "https://example.com/updated-photo.jpg"
  }
}

###
# Create a new feature
POST http://localhost:8081/api/features
Content-Type: application/json

{
  "featureName": "New Feature",
  "description": "This is a test feature",
  "photo": {
    "name": "Test Photo",
    "desc": "A test photo",
    "link": "https://example.com/test.jpg"
  },
} 
###
# Create a new assessment result
POST {{baseurl}}/api/results
Content-Type: application/json

{
    "User": "640e316ceebb6807bae74c7b",
    "Segment": "64694d4eebcfe8e7f004dfc8",
    "lineChoice": ["Choice1", "Choice2"],
    "Score": 85
}

###
# Get all assessment results
GET {{baseurl}}/api/results

###
# Get a specific assessment result by ID
GET {{baseurl}}/api/results/6528253a90360848d61e0372

###
# Update an assessment result by ID
PUT {{baseurl}}/api/results/6528253a90360848d61e0372  
Content-Type: application/json

{
    "User": "640e316ceebb6807bae74c7b",
    "Segment": "64694d4eebcfe8e7f004dfc8",
    "lineChoice": ["Choice1", "Choice2"],
    "Score": 90
}

###
# Delete an assessment result by ID
DELETE {{baseurl}}/api/results/657344d3789b77f2ae8d236a

### Get All Assessments for a User
# Set the username you want to search for
GET {{baseurl}}/api/results/user/testbikes

### get photos
GET {{baseurl}}/images/getAll

### Get photo by id
GET {{baseurl}}/images/656f872b19113e0adce02c8a

### Get photo by segementID
GET {{baseurl}}/images/getImages/65721b5a21ec846e04be6bf7

### Follow a user
{{baseurl}}/following/followers/follow
Content-Type: application/json
{
  "userId": "654e930f78f09598d1a80561",
  "targetUserId": "640e316ceebb6807bae74c7b"
}

### get following count
GET {{baseurl}}/following/following/count/DerekMartineau

### get all public assessments
GET {{baseurl}}/api/public-assessments

### Gets a list of the users that are followed from the logged-in users
{{baseurl}}/following/following/640e316ceebb6807bae74c7b

### get all post by userID
{{baseurl}}/results/user/public/640e316ceebb6807bae74c7b

###get all posts from users their following

{{baseurl}}/feed/assessment-results/testbikes

### get username from userID
{{baseurl}}/user/userid/654e93c078f09598d1a80646

######################################Feedback##########################

### get all feedback
GET {{baseurl}}/feedback/getAll

### create a feedback message
POST {{baseurl}}/feedback/create
Content-Type: application/json

{
    "Star": 1,
    "Name": "Test",
    "Email": "test@test.com",
    "IssueType": "Feedback",
    "Message": "This is a Test"
}

### delete feedback by ID
DELETE {{baseurl}}/feedback/delete/65aad714064d1834f8b6ca8c

####################################Tournaments######################
### create tournament
POST {{baseurl}}/tournaments/create
Content-Type: application/json

{
    "locationPark": "Bike Park A",
    "locationSegment": "65721b5a21ec846e04be6bf7",
    "startDate": "2024-02-28T17:00:00.000Z",  
    "endDate": "2024-02-28T17:00:00.000Z",    
    "gender": "male",
    "age": "18-35"
}

### Delete All Tournaments ###
DELETE {{baseurl}}/tournaments/deleteAll

### Delete Tournament By ID ###
# Replace ":id" with the ID of the tournament you want to delete
DELETE {{baseurl}}/tournaments/deleteById/:id
